#!/usr/bin/env bash

set -eo pipefail

go install github.com/alexfalkowski/gocovmerge/v2@v2.32.0
go install golang.org/x/vuln/cmd/govulncheck@v1.6.0
go install gotest.tools/gotestsum@v1.13.0
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.48.0
go install github.com/dkorunic/betteralign/cmd/betteralign@v0.14.2
go install github.com/loov/goda@v0.9.4
go install github.com/air-verse/air@v1.65.3
go install github.com/lasorda/protobuf-language-server@v0.1.2
