#!/usr/bin/env bash

set -e

function new_version() {
    readonly version=$1

    curl -sSOL https://go.dev/dl/go"$version".linux-amd64.tar.gz

    sudo rm -rf "$HOME"/go
    tar -C "$HOME" -xzf go"$version".linux-amd64.tar.gz

    rm go"$version".linux-amd64.tar.gz
}

function deps() {
    go install github.com/alexfalkowski/gocovmerge@v1.6.0
    go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
    go install gotest.tools/gotestsum@v1.12.1
    go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.32.0
    go install github.com/loov/goda@latest
    go install github.com/air-verse/air@v1.61.7
    go install github.com/lasorda/protobuf-language-server@latest
}

readonly kind=$1

case $kind in
  new)
    new_version "$2"
    ;;

  deps)
    deps
    ;;

  all)
    new_version "$2"
    deps
    ;;
esac
