#!/usr/bin/env bash

set -e

readonly version="ruby-3.4.1"
readonly file="$version".tar.gz

curl -sSOL https://cache.ruby-lang.org/pub/ruby/3.4/"$file"

sudo rm -rf "$HOME"/"$version"
tar -C "$HOME" -xzf "$file"

(
  cd "$HOME"/"$version"
  ./configure
  make
  sudo make install
)

rm "$file"
