#!/usr/bin/env bash
# shellcheck disable=SC1091

set -eo pipefail

# To run locally, run the following commands:
# - ~/code/standort/standort server -i file:config/standort.yml
# - ~/code/bezeichner/bezeichner server -i file:config/bezeichner.yml

source "$(dirname "$0")"/lib/dirs.sh
readonly kind=$1
readonly service=$2

case $kind in
  http)
    case $service in
    standort)
      echo "POST http://localhost:11002/standort.v2.Service/GetLocation" | vegeta attack -duration=30s -body "data/standort.json" -header "Content-Type: application/json" | tee "data/standort.bin" | vegeta report
      ;;
    bezeichner)
      echo "POST http://localhost:11001/bezeichner.v1.Service/GenerateIdentifiers" | vegeta attack -duration=30s -body "data/bezeichner.json" -header "Content-Type: application/json" | tee "data/bezeichner.bin" | vegeta report
      ;;
    esac
    ;;
  grpc)
    case $service in
    standort)
      ghz --insecure -n 2000 -c 20 --call standort.v2.Service/GetLocation -d '{ "ip": "92.211.2.113" }' localhost:12002
      ;;
    bezeichner)
      ghz --insecure -n 2000 -c 20 --call bezeichner.v1.Service/GenerateIdentifiers -d '{ "application": "ulid", "count": 10 }' localhost:12001
      ;;
    esac
    ;;
esac
