#!/usr/bin/env bash

set -e

path=$(dirname "$0")
readonly kind=$1

case $kind in
    bezeichner)
        host="https://bezeichner.lean-thoughts.com/bezeichner.v1.Service/GenerateIdentifiers"
        ;;
    standort)
        host="https://standort.lean-thoughts.com/standort.v2.Service/GetLocation"
        ;;

esac

# Remove old run.
rm -f "$path/$kind.bin"

# Perform the load test.
echo "POST $host" | vegeta attack -duration=30s -body "$path/$kind.json" -header "Content-Type: application/json" | tee "$path/$kind.bin" | vegeta report
