#!/usr/bin/env ruby
# frozen_string_literal: true

kind = ARGV[0]
deps = if kind == 'lib'
         `make outdated-dep`.split("\n").drop(1)
       elsif kind == 'svc'
         `make go-outdated-dep`.split("\n").drop(1)
       else
         []
       end

deps.each do |d|
  m, = d.split

  if kind == 'lib'
    `make module=#{m} update-dep`
  elsif kind == 'svc'
    `make module=#{m} go-update-dep`
  end
end
