#!/usr/bin/env bash

set -eo pipefail

# Make sure we are up to date.
make dep

# Services have ruby in the test folder.
if [ -f test/Gemfile ]; then
  (cd test && bundle exec ruby-lsp)
else
  bundle exec ruby-lsp
fi
