#!/usr/bin/env bash
# shellcheck disable=SC1010

set -eo pipefail

readonly libs=("$HOME/code/alexfalkowski.github.io" "$HOME/code/docker" "$HOME/code/go-service" "$HOME/code/go-signal" "$HOME/code/go-sync" "$HOME/code/gocovmerge" "$HOME/code/infraops" "$HOME/code/nonnative" "$HOME/code/tausch")
readonly services=("$HOME/code/go-client-template" "$HOME/code/go-service-template" "$HOME/code/bezeichner" "$HOME/code/migrieren" "$HOME/code/standort" "$HOME/code/status" "$HOME/code/web" "$HOME/code/go-monolith")
readonly dirs=("${libs[@]}" "${services[@]}")
readonly action=$1

case $action in
latest)
  for dir in "${dirs[@]}"; do
    (cd "$dir" && make latest)
  done
  ;;

purge)
  for dir in "${dirs[@]}"; do
    (cd "$dir" && make purge)
  done
  ;;

submodule)
  for dir in "${dirs[@]}"; do
    (cd "$dir" && update-submodule "$2" "$3")
  done
  ;;

ci)
  for dir in "${dirs[@]}"; do
    (cd "$dir" && update-ci)
  done
  ;;

done)
  for dir in "${dirs[@]}"; do
    (cd "$dir" && make done)
  done
  ;;
esac
