#!/usr/bin/env bash
# shellcheck disable=SC1010,SC1091,SC2154

set -eo pipefail

source "$(dirname "$0")"/lib/dirs.sh
readonly action=$1
readonly directories=("${services[@]}" "${ruby[@]}")

case $action in
new)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-ruby-dep "$2" "$3")
  done
  ;;

latest)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make latest)
  done
  ;;

purge)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make purge)
  done
  ;;

dep)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make dep)
  done
  ;;

bundler)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-bundler "$2" "$3")
  done
  ;;

submodule)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-submodule "$2" "$3")
  done
  ;;

ci)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-ci)
  done
  ;;

done)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make done)
  done
  ;;
esac
