#!/usr/bin/env bash
# shellcheck disable=SC1010,SC1091,SC2154

set -eo pipefail

source "$(dirname "$0")"/lib/dirs.sh
readonly dirs=$1
readonly action=$2

case $dirs in
ruby)
  readonly directories=("${ruby[@]}")
  ;;

services)
  readonly directories=("${services[@]}")
  ;;

all)
  readonly directories=("${services[@]}" "${ruby[@]}")
  ;;
esac

case $action in
new)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-ruby-dep "$3" "$4")
  done
  ;;

bundler)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-bundler "$3" "$4")
  done
  ;;

done)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make done)
  done
  ;;
esac
