#!/usr/bin/env bash
# shellcheck disable=SC1010,SC1091,SC2154

set -eo pipefail

source "$(dirname "$0")"/lib/dirs.sh
readonly action=$1

case $action in
new)
  for dir in "${services[@]}"; do
    (cd "$dir" && update-service-dep "$2" "$3")
  done
  ;;

done)
  for dir in "${services[@]}"; do
    (cd "$dir" && make done)
  done
  ;;
esac
