#!/usr/bin/env bash

set -eo pipefail

readonly version=$1
readonly desc=$2

make name=deps new-test

# Services have ruby in the test folder.
if [ -f test/Gemfile ]; then
  (cd test && gem install bundler -v "$version")
  make submodule ruby-update-bundler
else
  gem install bundler -v "$version"
  make submodule update-bundler
fi

make msg="upgraded bundler to $version" desc="${desc}" ready
