#!/usr/bin/env bash
# shellcheck disable=SC1010,SC1091,SC2154

set -eo pipefail

source "$(dirname "$0")"/lib/dirs.sh
readonly dirs=$1
readonly action=$2

case $dirs in
ruby)
  readonly directories=("${ruby[@]}")
  ;;

go)
  readonly directories=("${go[@]}")
  ;;

services)
  readonly directories=("${services[@]}")
  ;;

all)
  readonly directories=("${all[@]}")
  ;;

esac

case $action in
latest)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make latest)
  done
  ;;

purge)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make purge)
  done
  ;;

dep)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make dep)
  done
  ;;

submodule)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-submodule "$3" "$4")
  done
  ;;

ci)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-ci)
  done
  ;;

clean)
  for dir in "${directories[@]}"; do
    (cd "$dir" && clean)
  done
  ;;

done)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make done)
  done
  ;;

esac
