#!/usr/bin/env bash

set -e

readonly kind=$1
readonly version=$2
readonly desc=$3

make name=deps new-"${kind}"
make module=github.com/alexfalkowski/go-service/v2@"$version" go-get
make submodule go-dep ruby-update-all-dep
make msg="upgraded github.com/alexfalkowski/go-service/v2 to $version" desc="${desc}" ready
