#!/usr/bin/env bash
# shellcheck disable=SC1010

set -eo pipefail

readonly ruby=("$HOME/code/alexfalkowski.github.io" "$HOME/code/nonnative")
readonly go=("$HOME/code/go-service" "$HOME/code/go-signal" "$HOME/code/go-sync" "$HOME/code/gocovmerge" "$HOME/code/infraops" "$HOME/code/tausch" "$HOME/code/go-health")
readonly services=("$HOME/code/go-client-template" "$HOME/code/go-service-template" "$HOME/code/bezeichner" "$HOME/code/migrieren" "$HOME/code/standort" "$HOME/code/status" "$HOME/code/web" "$HOME/code/go-monolith")
readonly all=("${ruby[@]}" "${go[@]}" "${services[@]}")
readonly dirs=$1
readonly action=$2

case $dirs in
ruby)
  directories=("${ruby[@]}")
  ;;

go)
  directories=("${go[@]}")
  ;;

services)
  directories=("${services[@]}")
  ;;

all)
  directories=("${all[@]}")
  ;;

esac

case $action in
latest)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make latest)
  done
  ;;

purge)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make purge)
  done
  ;;

submodule)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-submodule "$3" "$4")
  done
  ;;

ci)
  for dir in "${directories[@]}"; do
    (cd "$dir" && update-ci)
  done
  ;;

done)
  for dir in "${directories[@]}"; do
    (cd "$dir" && make done)
  done
  ;;

esac
