version: 2.1

jobs:
  lint:
    docker:
      - image: alexfalkowski/ruby:2.0
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          name: restore deps
          keys:
            - scripts-ruby-cache-{{ checksum "Gemfile.lock" }}
            - scripts-ruby-cache-
      - run: make dep
      - run: make clean-dep
      - save_cache:
          name: save deps
          key: scripts-ruby-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor
      - run: make scripts-lint
      - run: make lint
    resource_class: arm.large
  sync:
    docker:
      - image: alexfalkowski/release:7.0
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: make sync push
    resource_class: arm.large
  version:
    docker:
      - image: alexfalkowski/release:7.0
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: version
      - run: package
    resource_class: arm.large
  wait-all:
    docker:
      - image: alexfalkowski/ruby:2.0
    steps:
      - run: echo "all applicable jobs finished"
    resource_class: arm.large

workflows:
  scripts:
    jobs:
      - lint
      - sync:
          requires:
            - lint
          filters:
            branches:
              ignore: master
      - version:
          context: gh
          serial-group: << pipeline.project.slug >>/version
          requires:
            - lint
          filters:
            branches:
              only: master
      - wait-all:
          requires:
            - lint
            - sync
            - version
