version: 2.1

jobs:
  lint:
    docker:
      - image: alexfalkowski/ruby:1.42
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          name: restore deps
          keys:
            - scripts-ruby-cache-{{ checksum "Gemfile.lock" }}
            - scripts-ruby-cache-
      - run: make dep
      - run: make clean-dep
      - save_cache:
          name: save deps
          key: scripts-ruby-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor
      - run: make scripts-lint
      - run: make lint
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.31
    steps:
      - checkout
      - run: release
    resource_class: large

workflows:
  scripts:
    jobs:
      - lint
      - release:
          context: gh
          requires:
            - lint
          filters:
            branches:
              only: master
