#!/usr/bin/env bash
# shellcheck disable=SC2155

set -eo pipefail

readonly script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

brew bundle --file="$script_dir/../Brewfile"

go install github.com/alexfalkowski/gocovmerge/v2@v2.35.0
go install golang.org/x/vuln/cmd/govulncheck@v1.8.0
go install gotest.tools/gotestsum@v1.13.0
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.50.0
go install github.com/dkorunic/betteralign/cmd/betteralign@v0.15.1
go install github.com/loov/goda@v0.10.1
go install github.com/air-verse/air@v1.67.4
go install github.com/lasorda/protobuf-language-server@v0.1.8
