#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2154,SC2155

set -eo pipefail

readonly root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$root_dir/lib/update.sh"
parse_update_args "$@"
set -- "${update_args[@]}"

readonly kind=$1
readonly version=$2
readonly desc="https://github.com/alexfalkowski/go-service/releases/tag/${version}"

if [ "$update_no_pr" = false ]; then
  make name=deps new-"${kind}"
fi
make module=github.com/alexfalkowski/go-service/v2@"$version" go-get
make submodule go-dep ruby-update-all-dep
if [ "$update_no_pr" = false ]; then
  make msg="upgraded github.com/alexfalkowski/go-service/v2 to $version" desc="${desc}" ready
fi
