#!/usr/bin/env ruby
# frozen_string_literal: true

require 'open3'

def make_output(*args)
  output, status = Open3.capture2('make', *args)
  abort("make #{args.join(' ')} failed") unless status.success?

  output.split("\n")
end

def make(*args)
  return if system('make', *args)

  abort("make #{args.join(' ')} failed")
end

if File.exist?('test/Gemfile')
  make_output('go-outdated-dep').each do |dep|
    mod, = dep.split
    make("module=#{mod}", 'go-update-dep')
  end
else
  make_output('outdated-dep').each do |dep|
    mod, = dep.split
    make("module=#{mod}", 'update-dep')
  end
end
