#!/usr/bin/env bash

set -eo pipefail

readonly kind=$1
readonly version=$2
readonly desc="https://github.com/alexfalkowski/go-service/releases/tag/${version}"

make name=deps new-"${kind}"
make module=github.com/alexfalkowski/go-service/v2@"$version" go-get
make submodule go-dep ruby-update-all-dep
make msg="upgraded github.com/alexfalkowski/go-service/v2 to $version" desc="${desc}" ready
