#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2154,SC2155

set -eo pipefail

readonly root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$root_dir/lib/update.sh"
parse_update_args "$@"
set -- "${update_args[@]}"

readonly version=$1
readonly desc=$2

if [ "$update_no_pr" = false ]; then
  make name=deps new-test
fi

# Services have ruby in the test folder.
if [ -f test/Gemfile ]; then
  (cd test && gem install bundler -v "$version")
  make submodule ruby-update-bundler
else
  gem install bundler -v "$version"
  make submodule update-bundler
fi

if [ "$update_no_pr" = false ]; then
  make msg="upgraded bundler to $version" desc="${desc}" ready
fi
